/* data.js */
const resources = [
  {"type":"channel","category":"Anime/AC","name":"SampleChannel","link":"https://t.me/sample"},
  {"type":"channel","category":"Adult","name":"SampleChannel","link":"https://t.me/sample"},
  {"type":"channel","category":"News","name":"SampleChannel","link":"https://t.me/sample"},
  {"type":"channel","category":"Local","name":"SampleChannel","link":"https://t.me/sample"},
  {"type":"channel","category":"Music","name":"SampleChannel","link":"https://t.me/sample"},
  {"type":"channel","category":"Film & TV","name":"SampleChannel","link":"https://t.me/sample"},
  {"type":"channel","category":"Games","name":"SampleChannel","link":"https://t.me/sample"},
  {"type":"channel","category":"Emotions","name":"SampleChannel","link":"https://t.me/sample"},
  {"type":"channel","category":"Community","name":"SampleChannel","link":"https://t.me/sample"},
  {"type":"channel","category":"Crypto","name":"SampleChannel","link":"https://t.me/sample"},
  {"type":"channel","category":"Programming","name":"SampleChannel","link":"https://t.me/sample"},
  {"type":"channel","category":"AI","name":"SampleChannel","link":"https://t.me/sample"},
  {"type":"channel","category":"Tech","name":"ASHED","link":"https://t.me/myashed"},
  {"type":"channel","category":"Finance","name":"SampleChannel","link":"https://t.me/sample"},
  {"type":"channel","category":"Travel","name":"SampleChannel","link":"https://t.me/sample"},
  {"type":"channel","category":"Novels","name":"SampleChannel","link":"https://t.me/sample"},
  {"type":"channel","category":"Live","name":"SampleChannel","link":"https://t.me/sample"},
  {"type":"channel","category":"Design","name":"SampleChannel","link":"https://t.me/sample"},
  {"type":"channel","category":"Education","name":"SampleChannel","link":"https://t.me/sample"},
  {"type":"channel","category":"Shopping","name":"SampleChannel","link":"https://t.me/sample"},

  {"type":"group","category":"Anime/AC","name":"SampleGroup","link":"https://t.me/sample"},
  {"type":"group","category":"Adult","name":"SampleGroup","link":"https://t.me/sample"},
  {"type":"group","category":"News","name":"SampleGroup","link":"https://t.me/sample"},
  {"type":"group","category":"Local","name":"SampleGroup","link":"https://t.me/sample"},
  {"type":"group","category":"Music","name":"SampleGroup","link":"https://t.me/sample"},
  {"type":"group","category":"Film & TV","name":"SampleGroup","link":"https://t.me/sample"},
  {"type":"group","category":"Games","name":"SampleGroup","link":"https://t.me/sample"},
  {"type":"group","category":"Emotions","name":"SampleGroup","link":"https://t.me/sample"},
  {"type":"group","category":"Community","name":"SampleGroup","link":"https://t.me/sample"},
  {"type":"group","category":"Crypto","name":"SampleGroup","link":"https://t.me/sample"},
  {"type":"group","category":"Programming","name":"SampleGroup","link":"https://t.me/sample"},
  {"type":"group","category":"AI","name":"SampleGroup","link":"https://t.me/sample"},
  {"type":"group","category":"Tech","name":"SampleGroup","link":"https://t.me/sample"},
  {"type":"group","category":"Finance","name":"SampleGroup","link":"https://t.me/sample"},
  {"type":"group","category":"Travel","name":"SampleGroup","link":"https://t.me/sample"},
  {"type":"group","category":"Novels","name":"SampleGroup","link":"https://t.me/sample"},
  {"type":"group","category":"Live","name":"SampleGroup","link":"https://t.me/sample"},
  {"type":"group","category":"Design","name":"SampleGroup","link":"https://t.me/sample"},
  {"type":"group","category":"Education","name":"SampleGroup","link":"https://t.me/sample"},
  {"type":"group","category":"Shopping","name":"SampleGroup","link":"https://t.me/sample"},

  {"type":"bot","category":"Anime/AC","name":"SampleBot","link":"https://t.me/sample"},
  {"type":"bot","category":"Adult","name":"SampleBot","link":"https://t.me/sample"},
  {"type":"bot","category":"News","name":"SampleBot","link":"https://t.me/sample"},
  {"type":"bot","category":"Local","name":"SampleBot","link":"https://t.me/sample"},
  {"type":"bot","category":"Music","name":"SampleBot","link":"https://t.me/sample"},
  {"type":"bot","category":"Film & TV","name":"SampleBot","link":"https://t.me/sample"},
  {"type":"bot","category":"Games","name":"SampleBot","link":"https://t.me/sample"},
  {"type":"bot","category":"Emotions","name":"SampleBot","link":"https://t.me/sample"},
  {"type":"bot","category":"Community","name":"SampleBot","link":"https://t.me/sample"},
  {"type":"bot","category":"Crypto","name":"SampleBot","link":"https://t.me/sample"},
  {"type":"bot","category":"Programming","name":"SampleBot","link":"https://t.me/sample"},
  {"type":"bot","category":"AI","name":"SampleBot","link":"https://t.me/sample"},
  {"type":"bot","category":"Tech","name":"SampleBot","link":"https://t.me/sample"},
  {"type":"bot","category":"Finance","name":"SampleBot","link":"https://t.me/sample"},
  {"type":"bot","category":"Travel","name":"SampleBot","link":"https://t.me/sample"},
  {"type":"bot","category":"Novels","name":"SampleBot","link":"https://t.me/sample"},
  {"type":"bot","category":"Live","name":"SampleBot","link":"https://t.me/sample"},
  {"type":"bot","category":"Design","name":"SampleBot","link":"https://t.me/sample"},
  {"type":"bot","category":"Education","name":"SampleBot","link":"https://t.me/sample"},
  {"type":"bot","category":"Shopping","name":"SampleBot","link":"https://t.me/sample"}
];
